### ISSUE TITLE
[Suggestion] add search box

### ISSUE THREAD

**Issue by lo8888** [ZeusJunior/tf2-automatic-gui#10]
Add a search menu for adding items with potentially photo of the item. Just like the bp.tf and bot.tf. It's gonna be pretty complicated i think but it is quite an improvement.

Besides, maybe add search box for existing item in the listings. But tbh, it isn't really practical imo. User can Ctrl F i think and it's the same thing

**Comment by ZeusJunior** [comment]
Search box in listings will be added with manual pricing, which i think i'll do after the speed branch is done

**Comment by ZeusJunior** [comment]
Done!
