### ISSUE TITLE
[Suggestions] Add temporary storage for user's input

### ISSUE THREAD

**Issue by lo8888** [ZeusJunior/tf2-automatic-gui#2]
The GUI breaks when a user tries to add more than a certain amount of listings at once. So maybe add some sort of temporary storage for the user's input and the GUI can add the listings without hitting the limit, which might cause the break.

**Comment by ZeusJunior** [comment]
https://github.com/ZeusJunior/tf2-automatic-gui/commit/663e2679dcbf0b2e5951dc3ec254c305b94cf77e
