### ISSUE TITLE
[Bug] Price sorting

### ISSUE THREAD

**Issue by Pocket-Deer** [ZeusJunior/tf2-automatic-gui#33]
**What is the problem?**
When sorting by the price of items, the wrong sorting algorithm is used. For examples:

> ![image](https://user-images.githubusercontent.com/58855174/74601842-117ecc00-50d5-11ea-8d0e-de2e345c1c00.png)

And if you look a little lower, then in this place the numbers are sorted by the "first digits", and not by the total value:

> ![image](https://user-images.githubusercontent.com/58855174/74601913-c2856680-50d5-11ea-8373-3ae12e593e05.png)

**How to reproduce:**
Just sort items for price from higher to lower

**Comment by ZeusJunior** [comment]
Fixed in dev, will be released in v1.7.1
