### ISSUE TITLE
[Bug] Won't delete all selected items

### ISSUE THREAD

**Issue by Pocket-Deer** [ZeusJunior/tf2-automatic-gui#34]
**What is the problem?**
Some items that are in the pricelist and marked with checkmarks are not removed from the pricelist.

**How to reproduce:**
1. On "Home" page, select "Show 25 entries"

> ![image](https://user-images.githubusercontent.com/58855174/74602101-037e7a80-50d8-11ea-8c04-8c74744c59ec.png)

2. Select every item on these first page of 25 items.

3. Try to delete this, click on "Delete Selected".

> (First try) ![image](https://user-images.githubusercontent.com/58855174/74602118-3163bf00-50d8-11ea-8063-bc54037c26ec.png)

> (Second try) ![image](https://user-images.githubusercontent.com/58855174/74602142-5fe19a00-50d8-11ea-9c5d-2f0497aeb072.png)

It can be less than 25.

**Comment by ZeusJunior** [comment]
Fixed in dev, will be released in v1.7.1
