### ISSUE TITLE
[Bug] Change minimum stock

### ISSUE THREAD

**Issue by Pocket-Deer** [ZeusJunior/tf2-automatic-gui#36]
**What is the problem?**
Won't change minimum tock, when the first number of maximum stock is less than minimum stock

**How to reproduce:**
1. Simply change the minimum stock from one item, for example ToD:
![image](https://user-images.githubusercontent.com/58855174/74623162-23647b80-5176-11ea-85c8-cb13ec6ff6bc.png)
![image](https://user-images.githubusercontent.com/58855174/74623177-2cede380-5176-11ea-89e4-d37b4731c9cf.png)
2. But if the first number of maximum stock has been more than number of minimum stock, then do this:
![image](https://user-images.githubusercontent.com/58855174/74623242-6c1c3480-5176-11ea-9b92-4f608d06a359.png)
![image](https://user-images.githubusercontent.com/58855174/74623246-750d0600-5176-11ea-8a6c-afe4885a3716.png)

_This bug can be the same as #33_

**Comment by ZeusJunior** [comment]
Fixed in dev, will be released in v1.7.1
