### ISSUE TITLE
[Error] Script breaks

### ISSUE THREAD

**Issue by lo8888** [ZeusJunior/tf2-automatic-gui#4]
The script breaks when there's an item failed to add and the user continues to add new items. For example, the user added an "Air Strike" to the listing and it failed, when the user tries to add other new items to the listings, the script breaks with an error.

Error: 

C:\Users\User\Desktop\tf2-automatic-gui-master\utils.js:292
                        if (pricelist[i].sku == items[j].sku) {
                                         ^

TypeError: Cannot read property 'sku' of undefined
    at C:\Users\User\Desktop\tf2-automatic-gui-master\utils.js:292:42
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
Press any key to continue . . .

**Comment by ZeusJunior** [comment]
Could you paste what you put in at first, and what you put in after, that caused the error.

**Comment by lo8888** [comment]
This is another crash but I might just put it here as well. https://imgur.com/a/yRgP9a7

**Comment by lo8888** [comment]
And update to the script break issue I mention above. It seems like it also happens when the user successfully add all the items, even without failed ones. The script will crash on the second attempt of adding new items. Screenshots: https://imgur.com/a/pTzcRRT

**Comment by ZeusJunior** [comment]
This should fix both of them, please test and let me know ^^

**Comment by lo8888** [comment]
Working fine now but there're still some items failed to add for some reasons.

**Comment by ZeusJunior** [comment]
Which?

**Comment by lo8888** [comment]
I don't really know tbh. I am adding 400+ listings at once and there're around 30 failed

**Comment by ZeusJunior** [comment]
Should only do that if its unable to get a price, will see about #3 later.
