### ISSUE TITLE
[Issue] Waiting For Localhost

### ISSUE THREAD

**Issue by lo8888** [ZeusJunior/tf2-automatic-gui#5]
Sometimes, the GUI takes a very long time with only a few listings in the adding box. There're no empty spaces after the final item so this issue is not caused by that. Maybe it's the limit of the price.tf token or other reasons.

**Comment by ZeusJunior** [comment]
The empty spaces was fixed in https://github.com/ZeusJunior/tf2-automatic-gui/commit/2428f704b047f979547b97c3b3044590830f701b 
Again, please copy paste your input here (or on pastebin) so i can reproduce

**Comment by lo8888** [comment]
https://imgur.com/a/xK3QePP

**Comment by ZeusJunior** [comment]
Small note
Its the balloonicorn, it refuses to go further after that item

**Comment by ZeusJunior** [comment]
This was also fixed in https://github.com/ZeusJunior/tf2-automatic-gui/commit/be1e85dc5452f994ce877e3d57b8ee0f220c1073
