### ISSUE TITLE
[Suggestion] Show price for item

### ISSUE THREAD

**Issue by DexGunner** [ZeusJunior/tf2-automatic-gui#76]
show item price with name on hover
![19;43;59 - 23 05 2020](https://user-images.githubusercontent.com/61100980/82735973-b04b4200-9d2e-11ea-90d4-4b7e8aa21d46.png)

**Comment by ZeusJunior** [comment]
I did say adding it to the item icon would make it too crowded, but i suppose it cant hurt on hover.

Need to know what it would look like with longer item names

**Comment by ZeusJunior** [comment]
Even with small text this doesn't really look very nice 
![image](https://user-images.githubusercontent.com/32263615/82741007-3dea5a00-9d4e-11ea-80cf-80e13775e3b1.png) ![image](https://user-images.githubusercontent.com/32263615/82741019-59edfb80-9d4e-11ea-84fb-aafdb9104ee1.png)

**Comment by DexGunner** [comment]
> Even with small text this doesn't really look very nice

try to reduce the distance between the lines

**Comment by arik123** [comment]
Added in dev
