### ISSUE TITLE
Not all items in the box are added

### ISSUE THREAD

**Issue by lo8888** [ZeusJunior/tf2-automatic-gui#8]
I added around 100 items to the box and only 30 were added.

Input: 
Strange Specialized Killstreak Air Strike
Strange Specialized Killstreak Ambassador
Strange Specialized Killstreak Atomizer
Strange Specialized Killstreak Australium Ambassador
Strange Specialized Killstreak Australium Black Box
Strange Specialized Killstreak Australium Flame Thrower
Strange Specialized Killstreak Australium Force-A-Nature
Strange Specialized Killstreak Australium Frontier Justice
Strange Specialized Killstreak Australium Grenade Launcher
Strange Specialized Killstreak Australium Knife
Strange Specialized Killstreak Australium Medi Gun
Strange Specialized Killstreak Australium Minigun
Strange Specialized Killstreak Australium Rocket Launcher
Strange Specialized Killstreak Australium Scattergun
Strange Specialized Killstreak Australium Sniper Rifle
Strange Specialized Killstreak Australium Stickybomb Launcher
Strange Specialized Killstreak Australium Tomislav
Strange Specialized Killstreak Australium Wrench
Strange Specialized Killstreak AWPer Hand
Strange Specialized Killstreak Axtinguisher
Strange Specialized Killstreak Back Scatter
Strange Specialized Killstreak Back Scratcher
Strange Specialized Killstreak Backburner
Strange Specialized Killstreak Battalion's Backup
Strange Specialized Killstreak Bazaar Bargain
Strange Specialized Killstreak Beggar's Bazooka
Strange Specialized Killstreak Big Earner
Strange Specialized Killstreak Black Box
Strange Specialized Killstreak Blutsauger
Strange Specialized Killstreak Bonk! Atomic Punch
Strange Specialized Killstreak Boston Basher
Strange Specialized Killstreak Brass Beast
Strange Specialized Killstreak Bread Bite
Strange Specialized Killstreak Buff Banner
Strange Specialized Killstreak Bushwacka
Strange Specialized Killstreak Candy Cane
Strange Specialized Killstreak Chargin' Targe
Strange Specialized Killstreak Claidheamh Mòr
Strange Specialized Killstreak Cleaner's Carbine
Strange Specialized Killstreak Cloak and Dagger
Strange Specialized Killstreak Concheror
Strange Specialized Killstreak Conniver's Kunai
Strange Specialized Killstreak Cow Mangler 5000
Strange Specialized Killstreak Crit-a-Cola
Strange Specialized Killstreak Crusader's Crossbow
Strange Specialized Killstreak Dead Ringer
Strange Specialized Killstreak Degreaser
Strange Specialized Killstreak Detonator
Strange Specialized Killstreak Diamondback
Strange Specialized Killstreak Direct Hit
Strange Specialized Killstreak Disciplinary Action
Strange Specialized Killstreak Enforcer
Strange Specialized Killstreak Equalizer
Strange Specialized Killstreak Escape Plan
Strange Specialized Killstreak Eyelander
Strange Specialized Killstreak Family Business
Strange Specialized Killstreak Fan O'War
Strange Specialized Killstreak Festive Ambassador
Strange Specialized Killstreak Festive Axtinguisher
Strange Specialized Killstreak Festive Backburner
Strange Specialized Killstreak Festive Black Box
Strange Specialized Killstreak Festive Bonesaw
Strange Specialized Killstreak Festive Buff Banner
Strange Specialized Killstreak Festive Crusader's Crossbow
Strange Specialized Killstreak Festive Eyelander
Strange Specialized Killstreak Festive Flame Thrower
Strange Specialized Killstreak Festive Flare Gun
Strange Specialized Killstreak Festive Force-A-Nature
Strange Specialized Killstreak Festive Frontier Justice
Strange Specialized Killstreak Festive Grenade Launcher
Strange Specialized Killstreak Festive Jarate
Strange Specialized Killstreak Festive Knife
Strange Specialized Killstreak Festive Medi Gun
Strange Specialized Killstreak Festive Minigun
Strange Specialized Killstreak Festive Revolver
Strange Specialized Killstreak Festive Rocket Launcher
Strange Specialized Killstreak Festive Sandvich
Strange Specialized Killstreak Festive Sapper
Strange Specialized Killstreak Festive Scattergun
Strange Specialized Killstreak Festive Shotgun
Strange Specialized Killstreak Festive SMG
Strange Specialized Killstreak Festive Sniper Rifle
Strange Specialized Killstreak Festive Stickybomb Launcher
Strange Specialized Killstreak Festive Ubersaw
Strange Specialized Killstreak Festive Wrangler
Strange Specialized Killstreak Festive Wrench
Strange Specialized Killstreak Flame Thrower
Strange Specialized Killstreak Flare Gun
Strange Specialized Killstreak Flying Guillotine
Strange Specialized Killstreak Force-A-Nature
Strange Specialized Killstreak Frontier Justice
Strange Specialized Killstreak Gloves of Running Urgently
Strange Specialized Killstreak Grenade Launcher
Strange Specialized Killstreak Half-Zatoichi
Strange Specialized Killstreak Hitman's Heatmaker
Strange Specialized Killstreak Holiday Punch
Strange Specialized Killstreak Homewrecker
Strange Specialized Killstreak Huo-Long Heater
Strange Specialized Killstreak Iron Bomber
Strange Specialized Killstreak Jag
Strange Specialized Killstreak Jarate
Strange Specialized Killstreak Killing Gloves of Boxing
Strange Specialized Killstreak Knife
Strange Specialized Killstreak Kritzkrieg
Strange Specialized Killstreak Kukri
Strange Specialized Killstreak L'Etranger
Strange Specialized Killstreak Liberty Launcher
Strange Specialized Killstreak Loch-n-Load
Strange Specialized Killstreak Mad Milk
Strange Specialized Killstreak Mantreads
Strange Specialized Killstreak Market Gardener
Strange Specialized Killstreak Medi Gun
Strange Specialized Killstreak Minigun
Strange Specialized Killstreak Mutated Milk
Strange Specialized Killstreak Natascha
Strange Specialized Killstreak Neon Annihilator
Strange Specialized Killstreak Original
Strange Specialized Killstreak Panic Attack
Strange Specialized Killstreak Persian Persuader
Strange Specialized Killstreak Phlogistinator
Strange Specialized Killstreak Pistol
Strange Specialized Killstreak Pomson 6000
Strange Specialized Killstreak Powerjack
Strange Specialized Killstreak Pretty Boy's Pocket Pistol
Strange Specialized Killstreak Quick-Fix
Strange Specialized Killstreak Quickiebomb Launcher
Strange Specialized Killstreak Red-Tape Recorder
Strange Specialized Killstreak Rescue Ranger
Strange Specialized Killstreak Reserve Shooter
Strange Specialized Killstreak Revolver
Strange Specialized Killstreak Righteous Bison
Strange Specialized Killstreak Rocket Launcher
Strange Specialized Killstreak Sandman
Strange Specialized Killstreak Sandvich
Strange Specialized Killstreak Scattergun
Strange Specialized Killstreak Scorch Shot
Strange Specialized Killstreak Scotsman's Skullcutter
Strange Specialized Killstreak Scottish Resistance
Strange Specialized Killstreak Shortstop
Strange Specialized Killstreak Shotgun
Strange Specialized Killstreak Snack Attack
Strange Specialized Killstreak Sniper Rifle
Strange Specialized Killstreak Soda Popper
Strange Specialized Killstreak Southern Hospitality
Strange Specialized Killstreak Splendid Screen
Strange Specialized Killstreak Spy-cicle
Strange Specialized Killstreak Stickybomb Launcher
Strange Specialized Killstreak Sydney Sleeper
Strange Specialized Killstreak Tomislav
Strange Specialized Killstreak Ubersaw
Strange Specialized Killstreak Vaccinator
Strange Specialized Killstreak Warrior's Spirit
Strange Specialized Killstreak Widowmaker
Strange Specialized Killstreak Winger
Strange Specialized Killstreak Wrangler
Strange Specialized Killstreak Wrench
Strange Specialized Killstreak Your Eternal Reward

Output in the website: 0 items added, 2 items failed, 28 items were already in your pricelist.

Logs from terminal: `Currently handling: 1104;11;kt-2
Currently handling: 61;11;kt-2
Currently handling: 450;11;kt-2
Currently handling: 61;11;australium;kt-2
Currently handling: 228;11;australium;kt-2
Currently handling: 21;11;australium;kt-2
Currently handling: 45;11;australium;kt-2
Currently handling: 141;11;australium;kt-2
Currently handling: 19;11;australium;kt-2
Currently handling: 4;11;australium;kt-2
Currently handling: 29;11;australium;kt-2
Currently handling: 15;11;australium;kt-2
Currently handling: 18;11;australium;kt-2
Currently handling: 13;11;australium;kt-2
Currently handling: 14;11;australium;kt-2
Currently handling: 20;11;australium;kt-2
Currently handling: 424;11;australium;kt-2
Currently handling: 7;11;australium;kt-2
Currently handling: 851;11;kt-2
Currently handling: 38;11;kt-2
Currently handling: 1103;11;kt-2
Currently handling: 326;11;kt-2
Currently handling: 40;11;kt-2
Currently handling: 226;11;kt-2
Currently handling: 402;11;kt-2
Currently handling: 730;11;kt-2
Currently handling: 461;11;kt-2
Currently handling: 228;11;kt-2
Queue empty, writing to file...
Currently handling: 36;11;kt-2`

**Comment by ZeusJunior** [comment]
`Strange Specialized Killstreak Bonk! Atomic Punch` is not a thing lol.
https://github.com/ZeusJunior/tf2-automatic-gui/commit/ba0935e480e42b86c1cbc8eab26a91eb17afb5fc fixed here
