### ISSUE TITLE
Website crashed(?)

### ISSUE THREAD

**Issue by lo8888** [ZeusJunior/tf2-automatic-gui#9]
The website crashed when I am adding a lot of listings. The terminal is still running so I guess it's fine.

"This page isn’t working localhost didn’t send any data.
ERR_EMPTY_RESPONSE
"

**Comment by ZeusJunior** [comment]
Yeah it does that. Haven't rly looked at how to change that

**Comment by ZeusJunior** [comment]
https://github.com/ZeusJunior/tf2-automatic-gui/tree/speed "fixed" this here
Made big changes, if you want to test them then go to the folder in console and type `git fetch` and then `git checkout speed`.
I've tested with ~870 items and it only took around 7 seconds total

Would be great if you could test and lmk of any issues again!
